sudo: false

language: node_js

cache:
  directories:
    - node_modules

install:
  - npm install

jobs:
  include:
    - stage: test
      script: npm run eslint
      script: npm run test:ci
    - stage: build
      script: npm run build
